# Generated by Django 5.2.7 on 2025-10-15 18:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlantillaInspeccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, unique=True, verbose_name='Nombre de la Plantilla')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción General')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PerfilTecnico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.ImageField(blank=True, null=True, upload_to='perfiles/fotos/', verbose_name='Foto de Perfil')),
                ('descripcion_profesional', models.TextField(blank=True, null=True, verbose_name='Descripción Profesional')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil_tecnico', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SolicitudInspeccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_cliente', models.CharField(max_length=100, verbose_name='Nombre de Contacto')),
                ('direccion', models.CharField(max_length=255, verbose_name='Dirección de la Inspección')),
                ('telefono', models.CharField(max_length=20, verbose_name='Teléfono de Contacto')),
                ('maquinaria', models.TextField(verbose_name='Maquinaria / Servicio Requerido')),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente de Aprobación'), ('APROBADA', 'Aprobada (Inspección Creada)'), ('RECHAZADA', 'Rechazada'), ('COMPLETADA', 'Inspección Finalizada')], default='PENDIENTE', max_length=20, verbose_name='Estado de la Solicitud')),
                ('motivo_rechazo', models.TextField(blank=True, null=True, verbose_name='Motivo del Rechazo (Admin)')),
                ('fecha_solicitud', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes_cliente', to=settings.AUTH_USER_MODEL, verbose_name='Cliente Solicitante')),
            ],
        ),
        migrations.CreateModel(
            name='Inspeccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_inspeccion', models.CharField(max_length=200, verbose_name='Título de la Inspección')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('comentarios_generales', models.TextField(blank=True, null=True, verbose_name='Comentarios Finales')),
                ('estado', models.CharField(choices=[('ASIGNADA', 'Asignada a Técnico'), ('EN_CURSO', 'En Curso (Borrador Guardado)'), ('COMPLETADA', 'Inspección Terminada')], default='ASIGNADA', max_length=50, verbose_name='Estado de la Inspección')),
                ('fecha_finalizacion', models.DateTimeField(blank=True, null=True)),
                ('tecnico', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inspecciones_asignadas', to=settings.AUTH_USER_MODEL, verbose_name='Técnico Asignado')),
                ('plantilla_base', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='usuarios.plantillainspeccion', verbose_name='Plantilla de Origen')),
                ('solicitud', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inspeccion_creada', to='usuarios.solicitudinspeccion', verbose_name='Solicitud de Origen')),
            ],
        ),
        migrations.CreateModel(
            name='TareaPlantilla',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=255, verbose_name='Descripción de la Tarea')),
                ('orden', models.IntegerField(default=1, verbose_name='Orden de Aparición')),
                ('plantilla', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tareas_base', to='usuarios.plantillainspeccion', verbose_name='Plantilla Maestra')),
            ],
            options={
                'verbose_name': 'Tarea de Plantilla',
                'verbose_name_plural': 'Tareas de Plantilla',
                'ordering': ['orden'],
            },
        ),
        migrations.CreateModel(
            name='TareaInspeccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=255, verbose_name='Punto de Control')),
                ('estado', models.CharField(choices=[('B', 'Bueno (Cumple)'), ('M', 'Malo (No Cumple)'), ('N/A', 'No Aplica'), ('PENDIENTE', 'Pendiente')], default='PENDIENTE', max_length=10, verbose_name='Resultado del Punto')),
                ('observacion', models.TextField(blank=True, null=True, verbose_name='Observación del Técnico')),
                ('inspeccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tareas', to='usuarios.inspeccion', verbose_name='Inspección Perteneciente')),
                ('plantilla_tarea', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='usuarios.tareaplantilla', verbose_name='Tarea Base')),
            ],
        ),
    ]
