# Generated by Django 5.2.7 on 2025-10-15 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solicitudinspeccion',
            name='cliente',
        ),
        migrations.AddField(
            model_name='solicitudinspeccion',
            name='apellido_cliente',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Apellido de Contacto'),
        ),
        migrations.AddField(
            model_name='solicitudinspeccion',
            name='observaciones_cliente',
            field=models.TextField(blank=True, null=True, verbose_name='Observaciones o Requerimientos Adicionales'),
        ),
    ]
