# Generated by Django 5.2.7 on 2025-11-21 01:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_solicitudinspeccion_cliente'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='inspeccion',
            name='fecha_programada',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha Programada'),
        ),
        migrations.AddField(
            model_name='solicitudinspeccion',
            name='detalle_cotizacion',
            field=models.TextField(blank=True, null=True, verbose_name='Detalle de la Cotización / Observaciones del Admin'),
        ),
        migrations.AddField(
            model_name='solicitudinspeccion',
            name='fecha_programada',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha Programada (Sugerida)'),
        ),
        migrations.AddField(
            model_name='solicitudinspeccion',
            name='monto_cotizacion',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True, verbose_name='Monto Cotizado (CLP)'),
        ),
        migrations.AddField(
            model_name='solicitudinspeccion',
            name='tecnico_asignado',
            field=models.ForeignKey(blank=True, limit_choices_to={'groups__name': 'Técnico'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordenes_asignadas', to=settings.AUTH_USER_MODEL, verbose_name='Técnico Pre-Asignado'),
        ),
        migrations.AlterField(
            model_name='solicitudinspeccion',
            name='estado',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente de Revisión (Admin)'), ('COTIZANDO', 'Pendiente de Aprobación (Cliente)'), ('APROBADA', 'Aprobada por Cliente (Orden de Trabajo Creada)'), ('COMPLETADA', 'Inspección Finalizada'), ('RECHAZADA', 'Rechazada por Admin/Cliente'), ('ANULADA', 'Anulada por Cliente')], default='PENDIENTE', max_length=25, verbose_name='Estado de la Solicitud'),
        ),
        migrations.AlterField(
            model_name='solicitudinspeccion',
            name='motivo_rechazo',
            field=models.TextField(blank=True, null=True, verbose_name='Motivo del Rechazo'),
        ),
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cambio_contrasena_obligatorio', models.BooleanField(default=True, verbose_name='Cambio de Contraseña Obligatorio')),
                ('foto', models.ImageField(blank=True, null=True, upload_to='perfiles/fotos/', verbose_name='Foto de Perfil')),
                ('descripcion', models.TextField(blank=True, max_length=500, null=True, verbose_name='Descripción Personal/Profesional')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='PerfilTecnico',
        ),
    ]
