# Generated by Django 5.2.7 on 2025-11-21 21:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_inspeccion_fecha_programada_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tareaplantilla',
            options={'ordering': ['orden']},
        ),
        migrations.RemoveField(
            model_name='perfil',
            name='cambio_contrasena_obligatorio',
        ),
        migrations.RemoveField(
            model_name='solicitudinspeccion',
            name='tecnico_asignado',
        ),
        migrations.AlterField(
            model_name='inspeccion',
            name='comentarios_generales',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='inspeccion',
            name='estado',
            field=models.CharField(choices=[('ASIGNADA', 'Asignada a Técnico'), ('EN_CURSO', 'En Curso'), ('COMPLETADA', 'Terminada')], default='ASIGNADA', max_length=20),
        ),
        migrations.AlterField(
            model_name='inspeccion',
            name='fecha_programada',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='inspeccion',
            name='nombre_inspeccion',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='inspeccion',
            name='plantilla_base',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='usuarios.plantillainspeccion'),
        ),
        migrations.AlterField(
            model_name='inspeccion',
            name='solicitud',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inspeccion', to='usuarios.solicitudinspeccion'),
        ),
        migrations.AlterField(
            model_name='inspeccion',
            name='tecnico',
            field=models.ForeignKey(limit_choices_to={'groups__name': 'Técnico'}, on_delete=django.db.models.deletion.PROTECT, related_name='inspecciones_asignadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='descripcion',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='perfiles/fotos/'),
        ),
        migrations.AlterField(
            model_name='plantillainspeccion',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='plantillainspeccion',
            name='nombre',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='solicitudinspeccion',
            name='apellido_cliente',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='solicitudinspeccion',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes_enviadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='solicitudinspeccion',
            name='detalle_cotizacion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='solicitudinspeccion',
            name='direccion',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='solicitudinspeccion',
            name='estado',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente de Revisión (Admin)'), ('COTIZANDO', 'Pendiente de Aprobación (Cliente)'), ('APROBADA', 'Aprobada (Orden Creada)'), ('COMPLETADA', 'Finalizada'), ('RECHAZADA', 'Rechazada'), ('ANULADA', 'Anulada por Cliente')], default='PENDIENTE', max_length=20),
        ),
        migrations.AlterField(
            model_name='solicitudinspeccion',
            name='fecha_programada',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='solicitudinspeccion',
            name='maquinaria',
            field=models.TextField(verbose_name='Maquinaria / Servicio'),
        ),
        migrations.AlterField(
            model_name='solicitudinspeccion',
            name='monto_cotizacion',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='solicitudinspeccion',
            name='motivo_rechazo',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='solicitudinspeccion',
            name='nombre_cliente',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='solicitudinspeccion',
            name='observaciones_cliente',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='solicitudinspeccion',
            name='telefono',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='tareainspeccion',
            name='descripcion',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='tareainspeccion',
            name='estado',
            field=models.CharField(choices=[('B', 'Bueno (Cumple)'), ('M', 'Malo (No Cumple)'), ('N/A', 'No Aplica'), ('PENDIENTE', 'Pendiente')], default='PENDIENTE', max_length=10),
        ),
        migrations.AlterField(
            model_name='tareainspeccion',
            name='inspeccion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tareas', to='usuarios.inspeccion'),
        ),
        migrations.AlterField(
            model_name='tareainspeccion',
            name='observacion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tareainspeccion',
            name='plantilla_tarea',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='usuarios.tareaplantilla'),
        ),
        migrations.AlterField(
            model_name='tareaplantilla',
            name='descripcion',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='tareaplantilla',
            name='orden',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='tareaplantilla',
            name='plantilla',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tareas_base', to='usuarios.plantillainspeccion'),
        ),
        migrations.AddIndex(
            model_name='inspeccion',
            index=models.Index(fields=['tecnico', 'estado'], name='usuarios_in_tecnico_8a565c_idx'),
        ),
    ]
