# Generated by Django 5.2.7 on 2025-11-10 23:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_perfilusuario'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfilusuario',
            name='usuario',
        ),
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cambio_contrasena_obligatorio', models.BooleanField(default=True, verbose_name='Cambio de Contraseña Obligatorio')),
                ('foto', models.ImageField(blank=True, null=True, upload_to='perfiles/fotos/', verbose_name='Foto de Perfil')),
                ('descripcion', models.TextField(blank=True, max_length=500, null=True, verbose_name='Descripción Personal/Profesional')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='PerfilTecnico',
        ),
        migrations.DeleteModel(
            name='PerfilUsuario',
        ),
    ]
