# Generated by Django 5.2.7 on 2025-11-14 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0005_remove_perfilusuario_usuario_perfil_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudinspeccion',
            name='motivo_anulacion',
            field=models.TextField(blank=True, null=True, verbose_name='Motivo de Solicitud de Anulación (Cliente)'),
        ),
        migrations.AlterField(
            model_name='solicitudinspeccion',
            name='estado',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente de Aprobación'), ('APROBADA', 'Aprobada (Inspección Creada)'), ('RECHAZADA', 'Rechazada'), ('COMPLETADA', 'Inspección Finalizada'), ('ANULACION_SOLICITADA', 'Anulación Solicitada'), ('ANULADA', 'Anulada')], default='PENDIENTE', max_length=25, verbose_name='Estado de la Solicitud'),
        ),
    ]
