# Generated by Django 5.2.8 on 2025-11-22 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0005_alter_tareaplantilla_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tareainspeccion',
            name='imagen_evidencia',
            field=models.ImageField(blank=True, null=True, upload_to='inspecciones/evidencias/', verbose_name='Imagen de Evidencia'),
        ),
        migrations.AlterField(
            model_name='tareainspeccion',
            name='descripcion',
            field=models.CharField(max_length=255, verbose_name='Punto de Control'),
        ),
        migrations.AlterField(
            model_name='tareainspeccion',
            name='estado',
            field=models.CharField(choices=[('B', 'Bueno (Cumple)'), ('M', 'Malo (No Cumple)'), ('N/A', 'No Aplica'), ('PENDIENTE', 'Pendiente')], default='PENDIENTE', max_length=50, verbose_name='Estado de la Tarea'),
        ),
    ]
