# Generated by Django 5.2.8 on 2025-11-22 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0006_tareainspeccion_imagen_evidencia_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='ciudad',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Ciudad'),
        ),
        migrations.AddField(
            model_name='perfil',
            name='direccion',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Dirección (Base)'),
        ),
        migrations.AddField(
            model_name='perfil',
            name='fecha_contratacion',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Contratación'),
        ),
        migrations.AddField(
            model_name='perfil',
            name='region',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Región'),
        ),
        migrations.AddField(
            model_name='perfil',
            name='rubro',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Rubro'),
        ),
        migrations.AddField(
            model_name='perfil',
            name='rut_empresa',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='RUT Empresa'),
        ),
        migrations.AddField(
            model_name='perfil',
            name='telefono',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Teléfono'),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='descripcion',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='Descripción / Bio'),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='perfiles/fotos/', verbose_name='Foto de Perfil'),
        ),
    ]
