# Generated by Django 5.2.7 on 2025-11-15 15:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0006_solicitudinspeccion_motivo_anulacion_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudinspeccion',
            name='monto_cotizacion',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True, verbose_name='Monto Cotizado (CLP)'),
        ),
        migrations.AddField(
            model_name='solicitudinspeccion',
            name='tecnico_asignado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordenes_asignadas', to=settings.AUTH_USER_MODEL, verbose_name='Técnico Pre-Asignado'),
        ),
        migrations.AlterField(
            model_name='solicitudinspeccion',
            name='estado',
            field=models.CharField(choices=[('PENDIENTE_ADMIN', 'Pendiente de Revisión (Admin)'), ('COTIZANDO', 'Pendiente de Aprobación (Cliente)'), ('APROBADA_CLIENTE', 'Aprobada por Cliente (Lista para Técnico)'), ('RECHAZADA', 'Rechazada por Admin/Cliente'), ('ANULADA', 'Anulada por Cliente'), ('EN_CURSO', 'En Curso (Técnico)'), ('COMPLETADA', 'Inspección Finalizada'), ('ANULACION_SOLICITADA', 'Anulación Solicitada')], default='PENDIENTE_ADMIN', max_length=25, verbose_name='Estado de la Solicitud'),
        ),
    ]
