# Generated by Django 5.2.7 on 2025-11-15 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0007_solicitudinspeccion_monto_cotizacion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inspeccion',
            name='fecha_programada',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha Programada'),
        ),
    ]
