# Generated by Django 5.2.8 on 2025-11-28 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0009_perfil_rut'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='obligar_cambio_contrasena',
            field=models.BooleanField(default=True, verbose_name='Obligar cambio de contraseña'),
        ),
    ]
