# Generated by Django 5.2.8 on 2025-12-02 01:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0010_perfil_obligar_cambio_contrasena'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudinspeccion',
            name='fecha_programada_preasignada',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='solicitudinspeccion',
            name='nombre_inspeccion_preasignado',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='solicitudinspeccion',
            name='plantilla_preasignada',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitudes_preasignadas', to='usuarios.plantillainspeccion'),
        ),
        migrations.AddField(
            model_name='solicitudinspeccion',
            name='tecnico_preasignado',
            field=models.ForeignKey(blank=True, limit_choices_to={'groups__name': 'Técnico'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitudes_preasignadas', to=settings.AUTH_USER_MODEL),
        ),
    ]
