# Generated by Django 5.2.7 on 2025-10-11 01:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Inspeccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_inspeccion', models.CharField(max_length=200, verbose_name='Nombre de la Inspección')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('comentarios_generales', models.TextField(blank=True, null=True)),
                ('completada', models.BooleanField(default=False)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TareaInspeccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=255, verbose_name='Punto de Control')),
                ('estado', models.CharField(choices=[('B', 'Bueno'), ('M', 'Malo'), ('N/A', 'No Aplica')], max_length=3)),
                ('observacion', models.TextField(blank=True, null=True)),
                ('inspeccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tareas', to='usuarios.inspeccion')),
            ],
        ),
    ]
