# Generated by Django 5.2.7 on 2025-11-21 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0005_alter_tareaplantilla_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='password_changed',
            field=models.BooleanField(default=False),
        ),
    ]
