# Generated by Django 5.2.8 on 2025-11-28 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0008_notificacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='cambio_clave_inicial_completado',
            field=models.BooleanField(default=False, verbose_name='Cambio de clave inicial completado'),
        ),
        migrations.AddField(
            model_name='perfil',
            name='certificaciones',
            field=models.TextField(blank=True, null=True, verbose_name='Certificaciones / Experiencia'),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='direccion',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Dirección'),
        ),
    ]
